<?php

namespace AppBundle\Repository;

/**
 * PrefectureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrefectureRepository extends \Doctrine\ORM\EntityRepository
{
}
