<?php

namespace AppBundle\Repository;

/**
 * ShowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByLatLng($neLat, $swLat, $neLng, $swLng){

        $query = $this->createQueryBuilder('s')
            ->where('s.lat < :neLat')
            ->andWhere('s.lat > :swLat')
            ->andWhere('s.lng < :neLng')
            ->andWhere('s.lng > :swLng')
            ->andWhere('s.is_converted = true')
            ->setMaxResults(500)
            ->setParameter('neLat', $neLat)
            ->setParameter('swLat', $swLat)
            ->setParameter('neLng', $neLng)
            ->setParameter('swLng', $swLng)
            ->getQuery();
        return $query->getResult();
    }

    public function findAllByPrefs(){

        $query = $this->createQueryBuilder('s')
            ->select('p.nameKanji', 'p.lat', 'p.lng', 'count(s.id)')
            ->innerJoin('AppBundle:Prefecture', 'p', 'WITH', 'p.id = s.pref_id')
            ->groupBy('p.id')
            ->orderBy('p.id')
            ->getQuery();
        return $query->getResult();
    }
}
